services:
  sander:
    runtime: nvidia
    command: /gitlab/python_basic/deep_learning/dl_machine_tools/run_jupyter_lab.sh
    image: gitlab-dv.tno.nl:4567/intelligent_imaging/python_basic/deep_learning
    ports:
     - $PORT:9007
    environment:
    - LD_LIBRARY_PATH=/usr/local/lib:/usr/local/cuda/lib64/stubs/
    - XDG_DATA_HOME=$HOME
    - XDG_CONFIG_HOME=$HOME/.config
    - HOME=$HOME
    - USER=$USER
    - NVIDIA_VISIBLE_DEVICES=0
    volumes:
    - /data/$USER/gitlab:/gitlab
    - /usr/local/certificates:/certificates
    - $HOME:$HOME
    - $PWD:/project
version: '2.3'


