version: '2.3'
services:
  thesis:
    build: .
    container_name:
      thesis
    runtime:
      nvidia
    shm_size:
      "8gb"
    stdin_open:
      true                    # docker run -i
    tty:
      true                    # docker run -t
    ports:
      - "9000"
    environment:
    - HOME=$HOME
    - USER=$USER
    - CUDA_VISIBLE_DEVICES=$GPU
    volumes:
    - ../:/project

