version: '3.4'

services:
  thesis:
    image: thesis-docker
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      # Map in authorized keys to enable logging in over SSH using PyCharm
      - $HOME/.ssh/authorized_keys:/root/.ssh/authorized_keys
    ports:
      - "22001"
    



