version: '3.4'

services:
  thesis:
    image: thesis-docker
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib:/usr/local/cuda/lib64/stubs/
      - XDG_DATA_HOME=$HOME
      - XDG_CONFIG_HOME=$HOME/.config
      - HOME=$HOME
      - USER=$USER
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      # Map in authorized keys to enable logging in over SSH using PyCharm
      - $HOME/.ssh/authorized_keys:/root/.ssh/authorized_keys
      - /data/$USER/gitlab:/gitlab
      - /usr/local/certificates:/certificates
      - $HOME:$HOME
      - $PWD:/project
    ports:
      - "9000:22"
    
