wandb_version: 1

Test name:
  desc: null
  value: split
Train names:
  desc: null
  value:
  - photo
Valid name:
  desc: null
  value:
  - art_painting
_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1650374128
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 13
      - 16
      4: 3.9.7
      5: 0.12.14
      8:
      - 5
batch_size:
  desc: null
  value: 128
epochs:
  desc: null
  value: 100
gamma:
  desc: null
  value: 2.5
learning_rate:
  desc: null
  value: 0.001
